// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iot-fronius.proto

/*
Package iot_fronius is a generated protocol buffer package.

It is generated from these files:
	iot-fronius.proto

It has these top-level messages:
	SuccessResponse
	Powerflow
	SitePowerflow
	InverterPowerflow
	OhmpilotPowerflow
	CurrentDataMeter
	MeterDetails
	CurrenDataMeterRequest
	CurrenDataInverterRequest
*/
package iot_fronius

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SuccessResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *SuccessResponse) Reset()                    { *m = SuccessResponse{} }
func (m *SuccessResponse) String() string            { return proto.CompactTextString(m) }
func (*SuccessResponse) ProtoMessage()               {}
func (*SuccessResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SuccessResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Powerflow struct {
	Site     *SitePowerflow       `protobuf:"bytes,1,opt,name=site" json:"site,omitempty"`
	Inverter []*InverterPowerflow `protobuf:"bytes,2,rep,name=inverter" json:"inverter,omitempty"`
	Ohmpilot []*OhmpilotPowerflow `protobuf:"bytes,3,rep,name=ohmpilot" json:"ohmpilot,omitempty"`
}

func (m *Powerflow) Reset()                    { *m = Powerflow{} }
func (m *Powerflow) String() string            { return proto.CompactTextString(m) }
func (*Powerflow) ProtoMessage()               {}
func (*Powerflow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Powerflow) GetSite() *SitePowerflow {
	if m != nil {
		return m.Site
	}
	return nil
}

func (m *Powerflow) GetInverter() []*InverterPowerflow {
	if m != nil {
		return m.Inverter
	}
	return nil
}

func (m *Powerflow) GetOhmpilot() []*OhmpilotPowerflow {
	if m != nil {
		return m.Ohmpilot
	}
	return nil
}

type SitePowerflow struct {
	Mode                    string  `protobuf:"bytes,1,opt,name=mode" json:"mode,omitempty"`
	BatteryStandby          bool    `protobuf:"varint,2,opt,name=batteryStandby" json:"batteryStandby,omitempty"`
	BackupMode              bool    `protobuf:"varint,3,opt,name=backupMode" json:"backupMode,omitempty"`
	PowerFromGrid           float64 `protobuf:"fixed64,4,opt,name=powerFromGrid" json:"powerFromGrid,omitempty"`
	PowerLoad               float64 `protobuf:"fixed64,5,opt,name=powerLoad" json:"powerLoad,omitempty"`
	PowerAkku               float64 `protobuf:"fixed64,6,opt,name=powerAkku" json:"powerAkku,omitempty"`
	PowerFromPv             float64 `protobuf:"fixed64,7,opt,name=powerFromPv" json:"powerFromPv,omitempty"`
	RelativeSelfConsumption uint32  `protobuf:"varint,8,opt,name=relativeSelfConsumption" json:"relativeSelfConsumption,omitempty"`
	RelativeAutonomy        uint32  `protobuf:"varint,9,opt,name=relativeAutonomy" json:"relativeAutonomy,omitempty"`
	MeterLocation           string  `protobuf:"bytes,10,opt,name=meterLocation" json:"meterLocation,omitempty"`
	EnergyDay               float64 `protobuf:"fixed64,11,opt,name=energyDay" json:"energyDay,omitempty"`
	EnergyYear              float64 `protobuf:"fixed64,12,opt,name=energyYear" json:"energyYear,omitempty"`
	EnergyTotal             float64 `protobuf:"fixed64,13,opt,name=energyTotal" json:"energyTotal,omitempty"`
}

func (m *SitePowerflow) Reset()                    { *m = SitePowerflow{} }
func (m *SitePowerflow) String() string            { return proto.CompactTextString(m) }
func (*SitePowerflow) ProtoMessage()               {}
func (*SitePowerflow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SitePowerflow) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *SitePowerflow) GetBatteryStandby() bool {
	if m != nil {
		return m.BatteryStandby
	}
	return false
}

func (m *SitePowerflow) GetBackupMode() bool {
	if m != nil {
		return m.BackupMode
	}
	return false
}

func (m *SitePowerflow) GetPowerFromGrid() float64 {
	if m != nil {
		return m.PowerFromGrid
	}
	return 0
}

func (m *SitePowerflow) GetPowerLoad() float64 {
	if m != nil {
		return m.PowerLoad
	}
	return 0
}

func (m *SitePowerflow) GetPowerAkku() float64 {
	if m != nil {
		return m.PowerAkku
	}
	return 0
}

func (m *SitePowerflow) GetPowerFromPv() float64 {
	if m != nil {
		return m.PowerFromPv
	}
	return 0
}

func (m *SitePowerflow) GetRelativeSelfConsumption() uint32 {
	if m != nil {
		return m.RelativeSelfConsumption
	}
	return 0
}

func (m *SitePowerflow) GetRelativeAutonomy() uint32 {
	if m != nil {
		return m.RelativeAutonomy
	}
	return 0
}

func (m *SitePowerflow) GetMeterLocation() string {
	if m != nil {
		return m.MeterLocation
	}
	return ""
}

func (m *SitePowerflow) GetEnergyDay() float64 {
	if m != nil {
		return m.EnergyDay
	}
	return 0
}

func (m *SitePowerflow) GetEnergyYear() float64 {
	if m != nil {
		return m.EnergyYear
	}
	return 0
}

func (m *SitePowerflow) GetEnergyTotal() float64 {
	if m != nil {
		return m.EnergyTotal
	}
	return 0
}

type InverterPowerflow struct {
	BatteryMode  string  `protobuf:"bytes,1,opt,name=batteryMode" json:"batteryMode,omitempty"`
	DeviceType   uint32  `protobuf:"varint,2,opt,name=deviceType" json:"deviceType,omitempty"`
	EnergyDay    float64 `protobuf:"fixed64,3,opt,name=energyDay" json:"energyDay,omitempty"`
	EnergyYear   float64 `protobuf:"fixed64,4,opt,name=energyYear" json:"energyYear,omitempty"`
	EnergyTotal  float64 `protobuf:"fixed64,5,opt,name=energyTotal" json:"energyTotal,omitempty"`
	CurrentPower float64 `protobuf:"fixed64,6,opt,name=currentPower" json:"currentPower,omitempty"`
	Soc          uint32  `protobuf:"varint,7,opt,name=soc" json:"soc,omitempty"`
}

func (m *InverterPowerflow) Reset()                    { *m = InverterPowerflow{} }
func (m *InverterPowerflow) String() string            { return proto.CompactTextString(m) }
func (*InverterPowerflow) ProtoMessage()               {}
func (*InverterPowerflow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InverterPowerflow) GetBatteryMode() string {
	if m != nil {
		return m.BatteryMode
	}
	return ""
}

func (m *InverterPowerflow) GetDeviceType() uint32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

func (m *InverterPowerflow) GetEnergyDay() float64 {
	if m != nil {
		return m.EnergyDay
	}
	return 0
}

func (m *InverterPowerflow) GetEnergyYear() float64 {
	if m != nil {
		return m.EnergyYear
	}
	return 0
}

func (m *InverterPowerflow) GetEnergyTotal() float64 {
	if m != nil {
		return m.EnergyTotal
	}
	return 0
}

func (m *InverterPowerflow) GetCurrentPower() float64 {
	if m != nil {
		return m.CurrentPower
	}
	return 0
}

func (m *InverterPowerflow) GetSoc() uint32 {
	if m != nil {
		return m.Soc
	}
	return 0
}

type OhmpilotPowerflow struct {
	PowerAcTotal float64 `protobuf:"fixed64,1,opt,name=powerAcTotal" json:"powerAcTotal,omitempty"`
	State        string  `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	Temperature  float64 `protobuf:"fixed64,3,opt,name=temperature" json:"temperature,omitempty"`
}

func (m *OhmpilotPowerflow) Reset()                    { *m = OhmpilotPowerflow{} }
func (m *OhmpilotPowerflow) String() string            { return proto.CompactTextString(m) }
func (*OhmpilotPowerflow) ProtoMessage()               {}
func (*OhmpilotPowerflow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OhmpilotPowerflow) GetPowerAcTotal() float64 {
	if m != nil {
		return m.PowerAcTotal
	}
	return 0
}

func (m *OhmpilotPowerflow) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *OhmpilotPowerflow) GetTemperature() float64 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

type CurrentDataMeter struct {
	CurrentAcPhase1                   float64       `protobuf:"fixed64,1,opt,name=currentAcPhase1" json:"currentAcPhase1,omitempty"`
	CurrentAcPhase2                   float64       `protobuf:"fixed64,2,opt,name=currentAcPhase2" json:"currentAcPhase2,omitempty"`
	CurrentAcPhase3                   float64       `protobuf:"fixed64,3,opt,name=currentAcPhase3" json:"currentAcPhase3,omitempty"`
	CurrentAcSum                      float64       `protobuf:"fixed64,4,opt,name=currentAcSum" json:"currentAcSum,omitempty"`
	MeterDetails                      *MeterDetails `protobuf:"bytes,5,opt,name=meterDetails" json:"meterDetails,omitempty"`
	Enable                            bool          `protobuf:"varint,6,opt,name=enable" json:"enable,omitempty"`
	EnergyReactiveVArAcPhase1Consumed uint32        `protobuf:"varint,7,opt,name=energyReactiveVArAcPhase1Consumed" json:"energyReactiveVArAcPhase1Consumed,omitempty"`
	EnergyReactiveVArAcPhase1Produced uint32        `protobuf:"varint,8,opt,name=energyReactiveVArAcPhase1Produced" json:"energyReactiveVArAcPhase1Produced,omitempty"`
	EnergyReactiveVArAcPhase2Consumed uint32        `protobuf:"varint,9,opt,name=energyReactiveVArAcPhase2Consumed" json:"energyReactiveVArAcPhase2Consumed,omitempty"`
	EnergyReactiveVArAcPhase2Produced uint32        `protobuf:"varint,10,opt,name=energyReactiveVArAcPhase2Produced" json:"energyReactiveVArAcPhase2Produced,omitempty"`
	EnergyReactiveVArAcPhase3Consumed uint32        `protobuf:"varint,11,opt,name=energyReactiveVArAcPhase3Consumed" json:"energyReactiveVArAcPhase3Consumed,omitempty"`
	EnergyReactiveVArAcPhase3Produced uint32        `protobuf:"varint,12,opt,name=energyReactiveVArAcPhase3Produced" json:"energyReactiveVArAcPhase3Produced,omitempty"`
	EnergyReactiveVArAcSumConsumed    uint32        `protobuf:"varint,13,opt,name=energyReactiveVArAcSumConsumed" json:"energyReactiveVArAcSumConsumed,omitempty"`
	EnergyReactiveVArAcSumProduced    uint32        `protobuf:"varint,14,opt,name=energyReactiveVArAcSumProduced" json:"energyReactiveVArAcSumProduced,omitempty"`
	EnergyRealWAcMinusAbsolute        uint32        `protobuf:"varint,15,opt,name=energyRealWAcMinusAbsolute" json:"energyRealWAcMinusAbsolute,omitempty"`
	EnergyRealWAcPhase1Consumed       uint32        `protobuf:"varint,16,opt,name=energyRealWAcPhase1Consumed" json:"energyRealWAcPhase1Consumed,omitempty"`
	EnergyRealWAcPhase1Produced       uint32        `protobuf:"varint,17,opt,name=energyRealWAcPhase1Produced" json:"energyRealWAcPhase1Produced,omitempty"`
	EnergyRealWAcPhase2Consumed       uint32        `protobuf:"varint,18,opt,name=energyRealWAcPhase2Consumed" json:"energyRealWAcPhase2Consumed,omitempty"`
	EnergyRealWAcPhase2Produced       uint32        `protobuf:"varint,19,opt,name=energyRealWAcPhase2Produced" json:"energyRealWAcPhase2Produced,omitempty"`
	EnergyRealWAcPhase3Consumed       uint32        `protobuf:"varint,20,opt,name=energyRealWAcPhase3Consumed" json:"energyRealWAcPhase3Consumed,omitempty"`
	EnergyRealWAcPhase3Produced       uint32        `protobuf:"varint,21,opt,name=energyRealWAcPhase3Produced" json:"energyRealWAcPhase3Produced,omitempty"`
	EnergyRealWAcPlusAbsolute         uint32        `protobuf:"varint,22,opt,name=energyRealWAcPlusAbsolute" json:"energyRealWAcPlusAbsolute,omitempty"`
	EnergyRealWAcSumConsumed          uint32        `protobuf:"varint,23,opt,name=energyRealWAcSumConsumed" json:"energyRealWAcSumConsumed,omitempty"`
	EnergyRealWAcSumProduced          uint32        `protobuf:"varint,24,opt,name=energyRealWAcSumProduced" json:"energyRealWAcSumProduced,omitempty"`
	FrequencyPhaseAverage             float64       `protobuf:"fixed64,25,opt,name=frequencyPhaseAverage" json:"frequencyPhaseAverage,omitempty"`
	MeterLocationCurrent              uint32        `protobuf:"varint,26,opt,name=meterLocationCurrent" json:"meterLocationCurrent,omitempty"`
	PowerApparentSPhase1              float64       `protobuf:"fixed64,27,opt,name=powerApparentSPhase1" json:"powerApparentSPhase1,omitempty"`
	PowerApparentSPhase2              float64       `protobuf:"fixed64,28,opt,name=powerApparentSPhase2" json:"powerApparentSPhase2,omitempty"`
	PowerApparentSPhase3              float64       `protobuf:"fixed64,29,opt,name=powerApparentSPhase3" json:"powerApparentSPhase3,omitempty"`
	PowerApparentSSum                 float64       `protobuf:"fixed64,30,opt,name=powerApparentSSum" json:"powerApparentSSum,omitempty"`
	PowerFactorPhase1                 float64       `protobuf:"fixed64,31,opt,name=powerFactorPhase1" json:"powerFactorPhase1,omitempty"`
	PowerFactorPhase2                 float64       `protobuf:"fixed64,32,opt,name=powerFactorPhase2" json:"powerFactorPhase2,omitempty"`
	PowerFactorPhase3                 float64       `protobuf:"fixed64,33,opt,name=powerFactorPhase3" json:"powerFactorPhase3,omitempty"`
	PowerFactorSum                    float64       `protobuf:"fixed64,34,opt,name=powerFactorSum" json:"powerFactorSum,omitempty"`
	PowerReactiveQPhase1              float64       `protobuf:"fixed64,35,opt,name=powerReactiveQPhase1" json:"powerReactiveQPhase1,omitempty"`
	PowerReactiveQPhase2              float64       `protobuf:"fixed64,36,opt,name=powerReactiveQPhase2" json:"powerReactiveQPhase2,omitempty"`
	PowerReactiveQPhase3              float64       `protobuf:"fixed64,37,opt,name=powerReactiveQPhase3" json:"powerReactiveQPhase3,omitempty"`
	PowerReactiveQSum                 float64       `protobuf:"fixed64,38,opt,name=powerReactiveQSum" json:"powerReactiveQSum,omitempty"`
	PowerRealPPhase1                  float64       `protobuf:"fixed64,39,opt,name=powerRealPPhase1" json:"powerRealPPhase1,omitempty"`
	PowerRealPPhase2                  float64       `protobuf:"fixed64,40,opt,name=powerRealPPhase2" json:"powerRealPPhase2,omitempty"`
	PowerRealPPhase3                  float64       `protobuf:"fixed64,41,opt,name=powerRealPPhase3" json:"powerRealPPhase3,omitempty"`
	PowerRealPSum                     float64       `protobuf:"fixed64,42,opt,name=powerRealPSum" json:"powerRealPSum,omitempty"`
	Timestamp                         uint32        `protobuf:"varint,43,opt,name=timestamp" json:"timestamp,omitempty"`
	Visible                           bool          `protobuf:"varint,44,opt,name=visible" json:"visible,omitempty"`
	VoltageAcPhase1                   float64       `protobuf:"fixed64,45,opt,name=voltageAcPhase1" json:"voltageAcPhase1,omitempty"`
	VoltageAcPhase2                   float64       `protobuf:"fixed64,46,opt,name=voltageAcPhase2" json:"voltageAcPhase2,omitempty"`
	VoltageAcPhase3                   float64       `protobuf:"fixed64,47,opt,name=voltageAcPhase3" json:"voltageAcPhase3,omitempty"`
}

func (m *CurrentDataMeter) Reset()                    { *m = CurrentDataMeter{} }
func (m *CurrentDataMeter) String() string            { return proto.CompactTextString(m) }
func (*CurrentDataMeter) ProtoMessage()               {}
func (*CurrentDataMeter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CurrentDataMeter) GetCurrentAcPhase1() float64 {
	if m != nil {
		return m.CurrentAcPhase1
	}
	return 0
}

func (m *CurrentDataMeter) GetCurrentAcPhase2() float64 {
	if m != nil {
		return m.CurrentAcPhase2
	}
	return 0
}

func (m *CurrentDataMeter) GetCurrentAcPhase3() float64 {
	if m != nil {
		return m.CurrentAcPhase3
	}
	return 0
}

func (m *CurrentDataMeter) GetCurrentAcSum() float64 {
	if m != nil {
		return m.CurrentAcSum
	}
	return 0
}

func (m *CurrentDataMeter) GetMeterDetails() *MeterDetails {
	if m != nil {
		return m.MeterDetails
	}
	return nil
}

func (m *CurrentDataMeter) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *CurrentDataMeter) GetEnergyReactiveVArAcPhase1Consumed() uint32 {
	if m != nil {
		return m.EnergyReactiveVArAcPhase1Consumed
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyReactiveVArAcPhase1Produced() uint32 {
	if m != nil {
		return m.EnergyReactiveVArAcPhase1Produced
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyReactiveVArAcPhase2Consumed() uint32 {
	if m != nil {
		return m.EnergyReactiveVArAcPhase2Consumed
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyReactiveVArAcPhase2Produced() uint32 {
	if m != nil {
		return m.EnergyReactiveVArAcPhase2Produced
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyReactiveVArAcPhase3Consumed() uint32 {
	if m != nil {
		return m.EnergyReactiveVArAcPhase3Consumed
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyReactiveVArAcPhase3Produced() uint32 {
	if m != nil {
		return m.EnergyReactiveVArAcPhase3Produced
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyReactiveVArAcSumConsumed() uint32 {
	if m != nil {
		return m.EnergyReactiveVArAcSumConsumed
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyReactiveVArAcSumProduced() uint32 {
	if m != nil {
		return m.EnergyReactiveVArAcSumProduced
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyRealWAcMinusAbsolute() uint32 {
	if m != nil {
		return m.EnergyRealWAcMinusAbsolute
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyRealWAcPhase1Consumed() uint32 {
	if m != nil {
		return m.EnergyRealWAcPhase1Consumed
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyRealWAcPhase1Produced() uint32 {
	if m != nil {
		return m.EnergyRealWAcPhase1Produced
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyRealWAcPhase2Consumed() uint32 {
	if m != nil {
		return m.EnergyRealWAcPhase2Consumed
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyRealWAcPhase2Produced() uint32 {
	if m != nil {
		return m.EnergyRealWAcPhase2Produced
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyRealWAcPhase3Consumed() uint32 {
	if m != nil {
		return m.EnergyRealWAcPhase3Consumed
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyRealWAcPhase3Produced() uint32 {
	if m != nil {
		return m.EnergyRealWAcPhase3Produced
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyRealWAcPlusAbsolute() uint32 {
	if m != nil {
		return m.EnergyRealWAcPlusAbsolute
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyRealWAcSumConsumed() uint32 {
	if m != nil {
		return m.EnergyRealWAcSumConsumed
	}
	return 0
}

func (m *CurrentDataMeter) GetEnergyRealWAcSumProduced() uint32 {
	if m != nil {
		return m.EnergyRealWAcSumProduced
	}
	return 0
}

func (m *CurrentDataMeter) GetFrequencyPhaseAverage() float64 {
	if m != nil {
		return m.FrequencyPhaseAverage
	}
	return 0
}

func (m *CurrentDataMeter) GetMeterLocationCurrent() uint32 {
	if m != nil {
		return m.MeterLocationCurrent
	}
	return 0
}

func (m *CurrentDataMeter) GetPowerApparentSPhase1() float64 {
	if m != nil {
		return m.PowerApparentSPhase1
	}
	return 0
}

func (m *CurrentDataMeter) GetPowerApparentSPhase2() float64 {
	if m != nil {
		return m.PowerApparentSPhase2
	}
	return 0
}

func (m *CurrentDataMeter) GetPowerApparentSPhase3() float64 {
	if m != nil {
		return m.PowerApparentSPhase3
	}
	return 0
}

func (m *CurrentDataMeter) GetPowerApparentSSum() float64 {
	if m != nil {
		return m.PowerApparentSSum
	}
	return 0
}

func (m *CurrentDataMeter) GetPowerFactorPhase1() float64 {
	if m != nil {
		return m.PowerFactorPhase1
	}
	return 0
}

func (m *CurrentDataMeter) GetPowerFactorPhase2() float64 {
	if m != nil {
		return m.PowerFactorPhase2
	}
	return 0
}

func (m *CurrentDataMeter) GetPowerFactorPhase3() float64 {
	if m != nil {
		return m.PowerFactorPhase3
	}
	return 0
}

func (m *CurrentDataMeter) GetPowerFactorSum() float64 {
	if m != nil {
		return m.PowerFactorSum
	}
	return 0
}

func (m *CurrentDataMeter) GetPowerReactiveQPhase1() float64 {
	if m != nil {
		return m.PowerReactiveQPhase1
	}
	return 0
}

func (m *CurrentDataMeter) GetPowerReactiveQPhase2() float64 {
	if m != nil {
		return m.PowerReactiveQPhase2
	}
	return 0
}

func (m *CurrentDataMeter) GetPowerReactiveQPhase3() float64 {
	if m != nil {
		return m.PowerReactiveQPhase3
	}
	return 0
}

func (m *CurrentDataMeter) GetPowerReactiveQSum() float64 {
	if m != nil {
		return m.PowerReactiveQSum
	}
	return 0
}

func (m *CurrentDataMeter) GetPowerRealPPhase1() float64 {
	if m != nil {
		return m.PowerRealPPhase1
	}
	return 0
}

func (m *CurrentDataMeter) GetPowerRealPPhase2() float64 {
	if m != nil {
		return m.PowerRealPPhase2
	}
	return 0
}

func (m *CurrentDataMeter) GetPowerRealPPhase3() float64 {
	if m != nil {
		return m.PowerRealPPhase3
	}
	return 0
}

func (m *CurrentDataMeter) GetPowerRealPSum() float64 {
	if m != nil {
		return m.PowerRealPSum
	}
	return 0
}

func (m *CurrentDataMeter) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CurrentDataMeter) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

func (m *CurrentDataMeter) GetVoltageAcPhase1() float64 {
	if m != nil {
		return m.VoltageAcPhase1
	}
	return 0
}

func (m *CurrentDataMeter) GetVoltageAcPhase2() float64 {
	if m != nil {
		return m.VoltageAcPhase2
	}
	return 0
}

func (m *CurrentDataMeter) GetVoltageAcPhase3() float64 {
	if m != nil {
		return m.VoltageAcPhase3
	}
	return 0
}

type MeterDetails struct {
	Manufacturer string `protobuf:"bytes,1,opt,name=manufacturer" json:"manufacturer,omitempty"`
	Model        string `protobuf:"bytes,2,opt,name=model" json:"model,omitempty"`
	Serial       string `protobuf:"bytes,3,opt,name=serial" json:"serial,omitempty"`
}

func (m *MeterDetails) Reset()                    { *m = MeterDetails{} }
func (m *MeterDetails) String() string            { return proto.CompactTextString(m) }
func (*MeterDetails) ProtoMessage()               {}
func (*MeterDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MeterDetails) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *MeterDetails) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *MeterDetails) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

type CurrenDataMeterRequest struct {
	Elements []*CurrentDataMeter `protobuf:"bytes,1,rep,name=elements" json:"elements,omitempty"`
}

func (m *CurrenDataMeterRequest) Reset()                    { *m = CurrenDataMeterRequest{} }
func (m *CurrenDataMeterRequest) String() string            { return proto.CompactTextString(m) }
func (*CurrenDataMeterRequest) ProtoMessage()               {}
func (*CurrenDataMeterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CurrenDataMeterRequest) GetElements() []*CurrentDataMeter {
	if m != nil {
		return m.Elements
	}
	return nil
}

type CurrenDataInverterRequest struct {
	DayEnergy   []int32 `protobuf:"varint,1,rep,packed,name=dayEnergy" json:"dayEnergy,omitempty"`
	Pac         []int32 `protobuf:"varint,2,rep,packed,name=pac" json:"pac,omitempty"`
	TotalEnergy []int32 `protobuf:"varint,3,rep,packed,name=totalEnergy" json:"totalEnergy,omitempty"`
	YearEnergy  []int32 `protobuf:"varint,4,rep,packed,name=yearEnergy" json:"yearEnergy,omitempty"`
	Timestamp   int64   `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *CurrenDataInverterRequest) Reset()                    { *m = CurrenDataInverterRequest{} }
func (m *CurrenDataInverterRequest) String() string            { return proto.CompactTextString(m) }
func (*CurrenDataInverterRequest) ProtoMessage()               {}
func (*CurrenDataInverterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CurrenDataInverterRequest) GetDayEnergy() []int32 {
	if m != nil {
		return m.DayEnergy
	}
	return nil
}

func (m *CurrenDataInverterRequest) GetPac() []int32 {
	if m != nil {
		return m.Pac
	}
	return nil
}

func (m *CurrenDataInverterRequest) GetTotalEnergy() []int32 {
	if m != nil {
		return m.TotalEnergy
	}
	return nil
}

func (m *CurrenDataInverterRequest) GetYearEnergy() []int32 {
	if m != nil {
		return m.YearEnergy
	}
	return nil
}

func (m *CurrenDataInverterRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*SuccessResponse)(nil), "iot_fronius.SuccessResponse")
	proto.RegisterType((*Powerflow)(nil), "iot_fronius.Powerflow")
	proto.RegisterType((*SitePowerflow)(nil), "iot_fronius.SitePowerflow")
	proto.RegisterType((*InverterPowerflow)(nil), "iot_fronius.InverterPowerflow")
	proto.RegisterType((*OhmpilotPowerflow)(nil), "iot_fronius.OhmpilotPowerflow")
	proto.RegisterType((*CurrentDataMeter)(nil), "iot_fronius.CurrentDataMeter")
	proto.RegisterType((*MeterDetails)(nil), "iot_fronius.MeterDetails")
	proto.RegisterType((*CurrenDataMeterRequest)(nil), "iot_fronius.CurrenDataMeterRequest")
	proto.RegisterType((*CurrenDataInverterRequest)(nil), "iot_fronius.CurrenDataInverterRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Fronius service

type FroniusClient interface {
	InsertCurrentDataPowerflow(ctx context.Context, in *Powerflow, opts ...grpc.CallOption) (*SuccessResponse, error)
	InsertCurrentDataMeter(ctx context.Context, in *CurrenDataMeterRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	InsertCurrentDataInverter(ctx context.Context, in *CurrenDataInverterRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
}

type froniusClient struct {
	cc *grpc.ClientConn
}

func NewFroniusClient(cc *grpc.ClientConn) FroniusClient {
	return &froniusClient{cc}
}

func (c *froniusClient) InsertCurrentDataPowerflow(ctx context.Context, in *Powerflow, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := grpc.Invoke(ctx, "/iot_fronius.Fronius/InsertCurrentDataPowerflow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *froniusClient) InsertCurrentDataMeter(ctx context.Context, in *CurrenDataMeterRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := grpc.Invoke(ctx, "/iot_fronius.Fronius/InsertCurrentDataMeter", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *froniusClient) InsertCurrentDataInverter(ctx context.Context, in *CurrenDataInverterRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := grpc.Invoke(ctx, "/iot_fronius.Fronius/InsertCurrentDataInverter", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Fronius service

type FroniusServer interface {
	InsertCurrentDataPowerflow(context.Context, *Powerflow) (*SuccessResponse, error)
	InsertCurrentDataMeter(context.Context, *CurrenDataMeterRequest) (*SuccessResponse, error)
	InsertCurrentDataInverter(context.Context, *CurrenDataInverterRequest) (*SuccessResponse, error)
}

func RegisterFroniusServer(s *grpc.Server, srv FroniusServer) {
	s.RegisterService(&_Fronius_serviceDesc, srv)
}

func _Fronius_InsertCurrentDataPowerflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Powerflow)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FroniusServer).InsertCurrentDataPowerflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_fronius.Fronius/InsertCurrentDataPowerflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FroniusServer).InsertCurrentDataPowerflow(ctx, req.(*Powerflow))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fronius_InsertCurrentDataMeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrenDataMeterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FroniusServer).InsertCurrentDataMeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_fronius.Fronius/InsertCurrentDataMeter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FroniusServer).InsertCurrentDataMeter(ctx, req.(*CurrenDataMeterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fronius_InsertCurrentDataInverter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrenDataInverterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FroniusServer).InsertCurrentDataInverter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_fronius.Fronius/InsertCurrentDataInverter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FroniusServer).InsertCurrentDataInverter(ctx, req.(*CurrenDataInverterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fronius_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iot_fronius.Fronius",
	HandlerType: (*FroniusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertCurrentDataPowerflow",
			Handler:    _Fronius_InsertCurrentDataPowerflow_Handler,
		},
		{
			MethodName: "InsertCurrentDataMeter",
			Handler:    _Fronius_InsertCurrentDataMeter_Handler,
		},
		{
			MethodName: "InsertCurrentDataInverter",
			Handler:    _Fronius_InsertCurrentDataInverter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iot-fronius.proto",
}

func init() { proto.RegisterFile("iot-fronius.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x58, 0xcd, 0x72, 0xdb, 0x36,
	0x17, 0x1d, 0x59, 0x76, 0x62, 0x41, 0x56, 0x6c, 0xe3, 0x73, 0x14, 0xd8, 0x71, 0xfc, 0x29, 0x4a,
	0x9a, 0xaa, 0xf9, 0x51, 0x27, 0x64, 0x17, 0x6d, 0xa6, 0xed, 0x54, 0x49, 0xea, 0x4c, 0x66, 0xe2,
	0xa9, 0x4a, 0x79, 0xda, 0xe9, 0x74, 0xd1, 0x42, 0x14, 0xec, 0x70, 0x4c, 0x12, 0x2c, 0x08, 0x2a,
	0xa3, 0x65, 0x1f, 0xa4, 0x9b, 0x6e, 0xbb, 0xec, 0xe3, 0xf4, 0x11, 0xfa, 0x12, 0x1d, 0x80, 0x10,
	0x08, 0x8a, 0x3f, 0xf2, 0xce, 0x38, 0xf7, 0xdc, 0xc3, 0x73, 0x71, 0x21, 0xf2, 0xc2, 0x60, 0xdf,
	0xa3, 0xfc, 0xd9, 0x05, 0xa3, 0xa1, 0x97, 0xc4, 0xc3, 0x88, 0x51, 0x4e, 0x61, 0xdb, 0xa3, 0xfc,
	0x17, 0x05, 0xf5, 0x9f, 0x80, 0xdd, 0x49, 0xe2, 0xba, 0x24, 0x8e, 0x1d, 0x12, 0x47, 0x34, 0x8c,
	0x09, 0x44, 0xe0, 0x66, 0x9c, 0x42, 0xa8, 0xd1, 0x6b, 0x0c, 0xb6, 0x9d, 0xe5, 0xb2, 0xff, 0x77,
	0x03, 0xb4, 0xc6, 0xf4, 0x03, 0x61, 0x17, 0x3e, 0xfd, 0x00, 0x87, 0x60, 0x33, 0xf6, 0x38, 0x91,
	0xa4, 0xb6, 0x75, 0x34, 0x34, 0x64, 0x87, 0x13, 0x8f, 0x13, 0xcd, 0x74, 0x24, 0x0f, 0xbe, 0x00,
	0xdb, 0x5e, 0x38, 0x27, 0x8c, 0x13, 0x86, 0x36, 0x7a, 0xcd, 0x41, 0xdb, 0x3a, 0xc9, 0xe5, 0xbc,
	0x55, 0xc1, 0x2c, 0x4f, 0xf3, 0x45, 0x2e, 0x7d, 0x1f, 0x44, 0x9e, 0x4f, 0x39, 0x6a, 0x96, 0xe4,
	0x7e, 0xa7, 0x82, 0x46, 0xee, 0x92, 0xdf, 0xff, 0xa7, 0x09, 0x3a, 0x39, 0x3f, 0x10, 0x82, 0xcd,
	0x80, 0xce, 0x52, 0xe7, 0x2d, 0x47, 0xfe, 0x0d, 0x1f, 0x81, 0x5b, 0x53, 0xcc, 0x39, 0x61, 0x8b,
	0x09, 0xc7, 0xe1, 0x6c, 0xba, 0x40, 0x1b, 0xb2, 0xf8, 0x15, 0x14, 0x9e, 0x00, 0x30, 0xc5, 0xee,
	0x55, 0x12, 0x9d, 0x09, 0x85, 0xa6, 0xe4, 0x18, 0x08, 0x7c, 0x08, 0x3a, 0x91, 0x78, 0xd0, 0x29,
	0xa3, 0xc1, 0x1b, 0xe6, 0xcd, 0xd0, 0x66, 0xaf, 0x31, 0x68, 0x38, 0x79, 0x10, 0x1e, 0x83, 0x96,
	0x04, 0xde, 0x51, 0x3c, 0x43, 0x5b, 0x92, 0x91, 0x01, 0x3a, 0x3a, 0xba, 0xba, 0x4a, 0xd0, 0x0d,
	0x23, 0x2a, 0x00, 0xd8, 0x03, 0x6d, 0x2d, 0x36, 0x9e, 0xa3, 0x9b, 0x32, 0x6e, 0x42, 0xf0, 0x73,
	0x70, 0x87, 0x11, 0x1f, 0x73, 0x6f, 0x4e, 0x26, 0xc4, 0xbf, 0x78, 0x45, 0xc3, 0x38, 0x09, 0x22,
	0xee, 0xd1, 0x10, 0x6d, 0xf7, 0x1a, 0x83, 0x8e, 0x53, 0x15, 0x86, 0x8f, 0xc1, 0xde, 0x32, 0x34,
	0x4a, 0x38, 0x0d, 0x69, 0xb0, 0x40, 0x2d, 0x99, 0x52, 0xc0, 0x45, 0xa5, 0x01, 0xe1, 0xc2, 0xb2,
	0x8b, 0xa5, 0x36, 0x90, 0xdb, 0x99, 0x07, 0x45, 0x2d, 0x24, 0x24, 0xec, 0x72, 0xf1, 0x1a, 0x2f,
	0x50, 0x3b, 0xad, 0x45, 0x03, 0x62, 0x37, 0xd3, 0xc5, 0x4f, 0x04, 0x33, 0xb4, 0x23, 0xc3, 0x06,
	0x22, 0x6a, 0x4d, 0x57, 0xe7, 0x94, 0x63, 0x1f, 0x75, 0xd2, 0x5a, 0x0d, 0xa8, 0xff, 0x6f, 0x03,
	0xec, 0x17, 0x4e, 0x8e, 0xc8, 0x53, 0x7d, 0x3b, 0xcb, 0x1a, 0x6d, 0x42, 0xe2, 0xc9, 0x33, 0x32,
	0xf7, 0x5c, 0x72, 0xbe, 0x88, 0x88, 0xec, 0x75, 0xc7, 0x31, 0x90, 0xbc, 0xef, 0x66, 0xbd, 0xef,
	0xcd, 0x75, 0xbe, 0xb7, 0x0a, 0xbe, 0x61, 0x1f, 0xec, 0xb8, 0x09, 0x63, 0x24, 0x4c, 0xcf, 0xac,
	0x6a, 0x73, 0x0e, 0x83, 0x7b, 0xa0, 0x19, 0x53, 0x57, 0x76, 0xb8, 0xe3, 0x88, 0x3f, 0xfb, 0x14,
	0xec, 0x17, 0x8e, 0xba, 0x90, 0x4a, 0x4f, 0x87, 0x9b, 0x3e, 0xad, 0x91, 0x4a, 0x99, 0x18, 0x3c,
	0x00, 0x5b, 0x31, 0xc7, 0x3c, 0xad, 0xb4, 0xe5, 0xa4, 0x0b, 0x61, 0x93, 0x93, 0x20, 0x22, 0x0c,
	0xf3, 0x84, 0x11, 0x55, 0xa6, 0x09, 0xf5, 0x7f, 0x3f, 0x00, 0x7b, 0xaf, 0x52, 0x4f, 0xaf, 0x31,
	0xc7, 0x67, 0xa2, 0xb7, 0x70, 0x00, 0x76, 0x95, 0xcf, 0x91, 0x3b, 0x7e, 0x8f, 0x63, 0xf2, 0x5c,
	0x3d, 0x73, 0x15, 0x2e, 0x32, 0x2d, 0x69, 0xa0, 0xc0, 0xb4, 0x8a, 0x4c, 0x5b, 0xd9, 0x59, 0x85,
	0x8d, 0x9d, 0x1b, 0xb9, 0x93, 0x24, 0x50, 0xbb, 0x9f, 0xc3, 0xe0, 0x57, 0x60, 0x47, 0x1e, 0xc3,
	0xd7, 0x84, 0x63, 0xcf, 0x8f, 0x65, 0x03, 0xda, 0xd6, 0x61, 0xee, 0x9d, 0x71, 0x66, 0x10, 0x9c,
	0x1c, 0x1d, 0x76, 0xc1, 0x0d, 0x12, 0xe2, 0xa9, 0x4f, 0x64, 0x5b, 0xb6, 0x1d, 0xb5, 0x82, 0xef,
	0xc0, 0xfd, 0xb4, 0x87, 0x0e, 0xc1, 0xae, 0xf8, 0x31, 0xfc, 0x30, 0x62, 0xcb, 0x5a, 0xd3, 0x9f,
	0x11, 0x99, 0xa9, 0x76, 0xad, 0x27, 0xd6, 0xaa, 0x8d, 0x19, 0x9d, 0x25, 0x2e, 0x99, 0xa9, 0x1f,
	0xec, 0x7a, 0x62, 0x9d, 0x9a, 0xa5, 0xbd, 0xb5, 0xea, 0xd5, 0xac, 0xeb, 0x78, 0xb3, 0xb4, 0x37,
	0xb0, 0x46, 0xed, 0x3a, 0xde, 0x6c, 0xed, 0xad, 0x5d, 0xaf, 0x66, 0x5f, 0xc7, 0x9b, 0xad, 0xbd,
	0xed, 0xac, 0x51, 0xd3, 0xde, 0x4e, 0xc1, 0x49, 0x09, 0x69, 0x92, 0x04, 0xda, 0x58, 0x47, 0x4a,
	0xad, 0x61, 0x55, 0xeb, 0x68, 0x4b, 0xb7, 0xea, 0x74, 0xb4, 0x9f, 0xaf, 0xc1, 0x91, 0x66, 0xf8,
	0x3f, 0x8e, 0xdc, 0x33, 0x2f, 0x4c, 0xe2, 0xd1, 0x34, 0xa6, 0x7e, 0xc2, 0x09, 0xda, 0x95, 0x1a,
	0x35, 0x0c, 0xf8, 0x0d, 0xb8, 0x9b, 0x8b, 0xae, 0x9c, 0xce, 0x3d, 0x29, 0x50, 0x47, 0xa9, 0x50,
	0xd0, 0x65, 0xec, 0x57, 0x2a, 0xe8, 0x1a, 0x4a, 0x15, 0xb2, 0x53, 0x08, 0xab, 0x14, 0xac, 0x7a,
	0x0f, 0xd9, 0xc9, 0xfb, 0x5f, 0xa5, 0x42, 0xbd, 0x87, 0xec, 0xb4, 0x1d, 0x54, 0x29, 0xd8, 0xf5,
	0x1e, 0xb2, 0x13, 0x76, 0xbb, 0x52, 0x41, 0x7b, 0xf8, 0x12, 0x1c, 0xe6, 0xc3, 0xbe, 0xd1, 0xca,
	0xae, 0xcc, 0xaf, 0x26, 0xc0, 0x17, 0x00, 0xe5, 0x82, 0xe6, 0x99, 0xbc, 0x23, 0x93, 0x2b, 0xe3,
	0x65, 0xb9, 0xda, 0x38, 0x2a, 0xcf, 0xd5, 0xae, 0x3f, 0x03, 0xb7, 0x2f, 0x18, 0xf9, 0x2d, 0x21,
	0xa1, 0xbb, 0x90, 0x05, 0x8d, 0xe6, 0x84, 0xe1, 0x4b, 0x82, 0x0e, 0xe5, 0x9b, 0xb6, 0x3c, 0x08,
	0x2d, 0x70, 0x90, 0xfb, 0xf2, 0xab, 0xaf, 0x06, 0x3a, 0x92, 0x4f, 0x2b, 0x8d, 0x89, 0x9c, 0xf4,
	0x2b, 0x15, 0x45, 0x58, 0x00, 0x13, 0xf5, 0x35, 0xb9, 0x2b, 0x1f, 0x54, 0x1a, 0xab, 0xc8, 0xb1,
	0xd0, 0x71, 0x65, 0x8e, 0x55, 0x91, 0x63, 0xa3, 0x7b, 0x95, 0x39, 0x36, 0x7c, 0x0a, 0xf6, 0xf3,
	0xb8, 0xf8, 0xd6, 0x9c, 0xc8, 0x84, 0x62, 0x40, 0xb3, 0x4f, 0xb1, 0xcb, 0x29, 0x53, 0x65, 0xfc,
	0xdf, 0x60, 0x9b, 0x81, 0x32, 0xb6, 0x85, 0x7a, 0xe5, 0x6c, 0xab, 0x8c, 0x6d, 0xa3, 0xfb, 0xe5,
	0x6c, 0x5b, 0x0c, 0xb2, 0x06, 0x28, 0x4c, 0xf7, 0x25, 0x75, 0x05, 0xd5, 0x7b, 0xb2, 0x7c, 0x11,
	0x7d, 0xaf, 0x4c, 0x3f, 0x30, 0xf6, 0x64, 0x25, 0x56, 0x91, 0x63, 0xa1, 0x87, 0x95, 0x39, 0x56,
	0x45, 0x8e, 0x8d, 0x3e, 0xaa, 0xcc, 0xc9, 0xf6, 0x5e, 0xe3, 0xa2, 0x8c, 0x47, 0x46, 0xc5, 0x66,
	0x40, 0x0c, 0xad, 0x4b, 0xd0, 0x1f, 0xab, 0x2a, 0x3e, 0x96, 0xe4, 0x02, 0x5e, 0xc2, 0xb5, 0xd0,
	0xa0, 0x94, 0x6b, 0x95, 0x70, 0x6d, 0xf4, 0x49, 0x29, 0xd7, 0xd6, 0x63, 0xbf, 0xc4, 0x84, 0xdb,
	0xc7, 0xc6, 0xd8, 0xbf, 0x04, 0xc5, 0x50, 0xc9, 0xbd, 0x80, 0xc4, 0x1c, 0x07, 0x11, 0x7a, 0x22,
	0x7f, 0x18, 0x19, 0x20, 0x2e, 0x5e, 0x73, 0x2f, 0xf6, 0xc4, 0xd8, 0xf1, 0x34, 0xbd, 0x78, 0xa9,
	0xa5, 0x18, 0x8e, 0xe6, 0xd4, 0xe7, 0xf8, 0x92, 0xe8, 0x81, 0xeb, 0x59, 0x3a, 0x1c, 0xad, 0xc0,
	0x45, 0xa6, 0x85, 0x86, 0x65, 0x4c, 0xab, 0xc8, 0xb4, 0xd1, 0xa7, 0x65, 0x4c, 0xbb, 0xff, 0x2b,
	0xd8, 0x31, 0x67, 0x25, 0x31, 0x80, 0x05, 0x38, 0x4c, 0x2e, 0xb0, 0x2b, 0x46, 0x44, 0xa6, 0xa6,
	0xeb, 0x1c, 0x26, 0xe6, 0x4d, 0x71, 0xad, 0xf2, 0x97, 0xf3, 0xa6, 0x5c, 0x88, 0xb9, 0x2a, 0x26,
	0xcc, 0xc3, 0xbe, 0x9c, 0xed, 0x5a, 0x8e, 0x5a, 0xf5, 0x27, 0xa0, 0x9b, 0xbe, 0x12, 0xf4, 0x8c,
	0xe9, 0x88, 0x57, 0x4c, 0xcc, 0xe1, 0x17, 0x60, 0x9b, 0xf8, 0x24, 0x20, 0x21, 0x17, 0xb7, 0x51,
	0x71, 0xf1, 0xbb, 0x97, 0x1b, 0xe2, 0x56, 0x67, 0x53, 0x47, 0xd3, 0xfb, 0x7f, 0x35, 0xc0, 0x61,
	0xa6, 0xba, 0xbc, 0x23, 0x2c, 0x85, 0x8f, 0x41, 0x6b, 0x86, 0x17, 0xdf, 0xca, 0x77, 0xa0, 0x54,
	0xde, 0x72, 0x32, 0x40, 0x4c, 0xde, 0x11, 0x76, 0xe5, 0x35, 0x75, 0xcb, 0x11, 0x7f, 0xca, 0x51,
	0x59, 0x4c, 0xd2, 0x2a, 0xa3, 0x29, 0x23, 0x26, 0x24, 0xee, 0x04, 0x0b, 0x82, 0x99, 0x22, 0x6c,
	0x4a, 0x82, 0x81, 0xe4, 0x9b, 0x2f, 0x06, 0xd2, 0xa6, 0xd1, 0x7c, 0xeb, 0x8f, 0x0d, 0x70, 0xf3,
	0x34, 0x2d, 0x0a, 0x3a, 0xe0, 0xe8, 0x6d, 0x18, 0x13, 0xc6, 0x8d, 0xea, 0xb2, 0x71, 0xbf, 0x9b,
	0xdb, 0x00, 0x8d, 0x1f, 0x1d, 0xe7, 0x6f, 0xe0, 0x2b, 0xb7, 0xfa, 0x9f, 0x41, 0xb7, 0xa0, 0x99,
	0x4e, 0xf3, 0x0f, 0x4a, 0x36, 0x74, 0xb5, 0x0f, 0x6b, 0xc4, 0x31, 0x38, 0x2c, 0x88, 0x2f, 0x37,
	0x1c, 0x3e, 0xaa, 0xd0, 0x5f, 0xe9, 0x48, 0xfd, 0x23, 0x5e, 0x3e, 0x07, 0x5d, 0x97, 0x06, 0x43,
	0x3c, 0x27, 0x97, 0x98, 0x0a, 0xe6, 0x50, 0x31, 0x5f, 0xee, 0xbe, 0xa5, 0x5c, 0xed, 0xdc, 0x98,
	0x51, 0x4e, 0xc7, 0x8d, 0x3f, 0x37, 0x9a, 0xce, 0xf9, 0x9b, 0xe9, 0x0d, 0xf9, 0xff, 0x0e, 0xfb,
	0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x17, 0x0e, 0x37, 0xa6, 0x04, 0x11, 0x00, 0x00,
}
